-- =========================================================
-- Migration 014: Add proposal_json column to training_ideas
-- Stores the full enterprise-grade proposal generated by AI.
-- This is the single source of truth — shared by all roles.
-- =========================================================

ALTER TABLE training_ideas
    ADD COLUMN IF NOT EXISTS proposal_json MEDIUMTEXT NULL DEFAULT NULL
        COMMENT 'Full structured proposal JSON generated by AI (full_proposal task type)'
    AFTER expected_output;

-- Add an index-friendly catalog_key column for fast catalog lookups
ALTER TABLE training_ideas
    ADD COLUMN IF NOT EXISTS catalog_key VARCHAR(120) NULL DEFAULT NULL
        COMMENT 'Matched catalog project key (e.g. face_recognition_attendance) or NULL for custom'
    AFTER proposal_json;
