<?php
require_once __DIR__ . '/config.php';
$db = db();
try {
    $db->exec("ALTER TABLE training_ideas ADD COLUMN proposal_json MEDIUMTEXT NULL DEFAULT NULL COMMENT 'Full structured proposal JSON generated by AI'");
    echo "Added proposal_json. ";
} catch (Exception $e) { echo "Err (json): " . $e->getMessage() . " "; }

try {
    $db->exec("ALTER TABLE training_ideas ADD COLUMN catalog_key VARCHAR(120) NULL DEFAULT NULL COMMENT 'Matched catalog project key'");
    echo "Added catalog_key.";
} catch (Exception $e) { echo "Err (key): " . $e->getMessage(); }
